#!/usr/bin/nft -f

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority filter; policy drop;
		ct state established,related accept
		iif "lo" accept
		icmp type echo-request accept
		icmpv6 type { echo-request, nd-neighbor-solicit, nd-neighbor-advert } accept
		tcp dport { 22, 80, 443, 21, 25, 53, 110, 143, 465, 587, 993, 995, 1500, 1501 } accept
		udp dport { 53 } accept
	}
	chain forward {
		type filter hook forward priority filter; policy accept;
		ct state established,related accept
	}
	chain output {
		type filter hook output priority filter; policy accept;
	}
}
